#!/usr/bin/env bash

# GLORY TO UKRAINE

source /usr/share/alexandrite/version

userspace_version=`dconf read /org/alexandriteos/userspace_version`

if [ -z "$userspace_version" ]; then
	dconf write /org/alexandriteos/userspace_version "310"
	userspace_version=310
fi

if (( "$version" > "$userspace_version" )); then
	bash /usr/share/system-updates/upd.sh
	dconf write /org/alexandriteos/userspace_version "${version}"
fi

exit 0
