#!/usr/bin/env bash

# GLORY TO UKRAINE

set -e

sleep 20

source /usr/share/alexandrite/version

latest_version=`curl https://alexandriteos.org/api/version`
#version=000

if (( "$version" < "$latest_version" )); then
	zenity --width 360 --warning --text="AlexandriteOSの新しいバージョンが利用可能です。 \nアプリケーションメニューにあるシステムアップデートというエントリーでアップデートを行ってください。" --title="AlexandriteOSシステム"
fi

exit 0
