#!/usr/bin/env bash

# GLORY TO UKRAINE

trap sigint sigint

function sigint() {
    echo -e "\e[31m Interrupted! \e[m"
    echo "中断されました。 ウィンドウを閉じて終了してください..."
    exit 1    
}

cat <<EOS
===============================
AlexandriteOS system updater v1.00

(c)2021-2022 Project Alexandrite

===============================

EOS


echo "update rpm packages..."
zypper refresh
zypper --non-interactive dup

echo "update flatpak packages...."
flatpak update -y

echo -e "\e[32m Done! \e[m"
echo "ウィンドウを閉じて終了してください..."
