on:
  push:                 
    branches:           
      - main    
name: Build and Deploy  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master    
      - name: build
        run: |
         sudo pip install kiwi
         sudo apt install zypper qemu-utils mtools docker-compose -y
         docker-compose up --build
         tar --zstd -cf astrust.osupd repo
         sudo ./mkiso.sh -t astrust
         sudo mv astrust.osupd out/

      - name: FTP Upload
        uses: SamKirkland/FTP-Deploy-Action@2.0.0   
        env:                                        
          FTP_SERVER: ${{ secrets.FTP_SERVER }}     
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }} 
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} 
          LOCAL_DIR: out
          REMOTE_DIR: "/data/astrust/autobuilds"



